# .github/workflows/deploy-edge-functions.yml
name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main
      - develop
    paths:
      # Trigger workflow only when functions change or the workflow file itself changes
      - 'supabase/functions/**'
      - '.github/workflows/deploy-edge-functions.yml'

jobs:
  deploy:
    name: Build and Deploy Edge Functions
    runs-on: ubuntu-latest

    # Use GitHub Environments to distinguish between staging and production deployments.
    # This also allows for environment-specific secrets and protection rules.
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
      # Optional: Add the URL to your Supabase project's functions page for easy access from the GitHub UI.
      # Replace the project IDs with your actual Supabase project IDs.
      url: ${{ github.ref == 'refs/heads/main' && 'https://supabase.com/dashboard/project/${{ secrets.SUPABASE_PROJECT_ID_PRODUCTION }}/functions' || 'https://supabase.com/dashboard/project/${{ secrets.SUPABASE_PROJECT_ID_STAGING }}/functions' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x # Use a specific version or v1.x for the latest stable

      - name: Set up Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Make deployment script executable
        run: chmod +x ./scripts/deploy-edge-functions.sh

      - name: Deploy to Staging Environment
        if: github.ref == 'refs/heads/develop'
        run: ./scripts/deploy-edge-functions.sh ${{ secrets.SUPABASE_PROJECT_ID_STAGING }}
        env:
          # This token is required for the Supabase CLI to authenticate.
          # Store it as a secret in your GitHub repository settings.
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deploy to Production Environment
        if: github.ref == 'refs/heads/main'
        run: ./scripts/deploy-edge-functions.sh ${{ secrets.SUPABASE_PROJECT_ID_PRODUCTION }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
